// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type BlogPostDocumentDataSlicesSlice =
  | CallToActionSlice
  | ScrollerSlice
  | ContentSlice
  | ImageWithTextSlice
  | HeroSlice

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the Post Title
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a short preview
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField

  /**
   * Date Published field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.date_published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_published: prismic.DateField

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    'blog_post',
    Lang
  >

type BrandDocumentDataSlicesSlice = ContentSlice

/**
 * Content for Brand documents
 */
interface BrandDocumentData {
  /**
   * Title field in *Brand*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Logo field in *Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Description field in *Brand*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Slice Zone field in *Brand*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BrandDocumentDataSlicesSlice> /**
   * Meta Description field in *Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: brand.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: brand.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Brand document from Prismic
 *
 * - **API ID**: `brand`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BrandDocumentData>, 'brand', Lang>

type HomepageDocumentDataSlicesSlice =
  | CallToActionSlice
  | ImageWithTextSlice
  | ContentSlice
  | ScrollerSlice
  | HeroSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

type PageDocumentDataSlicesSlice =
  | FormSlice
  | CallToActionSlice
  | ScrollerSlice
  | ContentSlice
  | ImageWithTextSlice
  | HeroSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * TItle field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the Page Title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

type PortfolioDocumentDataSlicesSlice =
  | CallToActionSlice
  | ScrollerSlice
  | ImageWithTextSlice
  | ContentSlice

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * Title field in *Portfolio*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the Project Title
   * - **API ID Path**: portfolio.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Date Published field in *Portfolio*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.date_published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_published: prismic.DateField

  /**
   * Featured Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Excerpt field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField

  /**
   * Slice Zone field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Description field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortfolioDocumentData>,
    'portfolio',
    Lang
  >

/**
 * Item in *Product → Files*
 */
export interface ProductDocumentDataFilesItem {
  /**
   * File field in *Product → Files*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: product.files[].file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField
}

type ProductDocumentDataSlicesSlice =
  | ScrollerSlice
  | ImageWithTextSlice
  | ContentSlice

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the Product Title
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Product Type field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_type: prismic.ContentRelationshipField<'product_type'>

  /**
   * Brand field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.brand
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brand: prismic.ContentRelationshipField<'brand'>

  /**
   * Featured Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Excerpt field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a shorter description
   * - **API ID Path**: product.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the product
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Files field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.files[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  files: prismic.GroupField<Simplify<ProductDocumentDataFilesItem>>

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ProductDocumentData>, 'product', Lang>

type ProductTypeDocumentDataSlicesSlice = ContentSlice

/**
 * Content for Product Type documents
 */
interface ProductTypeDocumentData {
  /**
   * Title field in *Product Type*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the Product Type Title
   * - **API ID Path**: product_type.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Featured Image field in *Product Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Excerpt field in *Product Type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a short product type description
   * - **API ID Path**: product_type.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField

  /**
   * Description field in *Product Type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the product type
   * - **API ID Path**: product_type.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Slice Zone field in *Product Type*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductTypeDocumentDataSlicesSlice> /**
   * Meta Description field in *Product Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product_type.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Product Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Product Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product_type.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Product Type document from Prismic
 *
 * - **API ID**: `product_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductTypeDocumentData>,
    'product_type',
    Lang
  >

type ServiceDocumentDataSlicesSlice =
  | CallToActionSlice
  | ScrollerSlice
  | ImageWithTextSlice
  | HeroSlice
  | ContentSlice

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Service Title
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Description field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the service
   * - **API ID Path**: service.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Excerpt field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a shorter description
   * - **API ID Path**: service.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ServiceDocumentData>, 'service', Lang>

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Settings → Footer Socials*
 */
export interface SettingsDocumentDataFooterSocialsItem {
  /**
   * Logo field in *Settings → Footer Socials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_socials[].logo
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  logo: prismic.SelectField<'Facebook' | 'Instagram' | 'LinkedIn' | 'Yelp'>

  /**
   * Social URL field in *Settings → Footer Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_socials[].social_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_url: prismic.LinkField
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Domain field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.domain
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  domain: prismic.KeyTextField

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Site Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_meta_description: prismic.KeyTextField

  /**
   * Site Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_meta_image: prismic.ImageField<never>

  /**
   * Site Theme field in *Settings*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_theme
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  site_theme: prismic.SelectField<'Base' | 'Alternate'>

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>

  /**
   * Footer Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>

  /**
   * Footer Socials field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_socials: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSocialsItem>
  >

  /**
   * Company Information field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter company info
   * - **API ID Path**: settings.company_information
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_information: prismic.RichTextField

  /**
   * Terms of Service field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter terms of service info
   * - **API ID Path**: settings.terms_of_service
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  terms_of_service: prismic.RichTextField

  /**
   * Design Credit field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optionally give credit to designers.
   * - **API ID Path**: settings.design_credit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  design_credit: prismic.RichTextField
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >

export type AllDocumentTypes =
  | BlogPostDocument
  | BrandDocument
  | HomepageDocument
  | PageDocument
  | PortfolioDocument
  | ProductDocument
  | ProductTypeDocument
  | ServiceDocument
  | SettingsDocument

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Button Link field in *CallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Label field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Call to Action
   * - **API ID Path**: call_to_action.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.button_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_color: prismic.SelectField<
    'Inverted' | 'Primary' | 'Secondary' | 'Ghost'
  >
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceFeaturedGridPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceFeaturedGridItem {
  /**
   * Icon field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select an Icon
   * - **API ID Path**: call_to_action.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    'RiQuestionnaireFill' | 'GiHomeGarage' | 'FaToolbox'
  >

  /**
   * Heading field in *CallToAction → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter a Call to Action
   * - **API ID Path**: call_to_action.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Button Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where should they go?
   * - **API ID Path**: call_to_action.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].button_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_color: prismic.SelectField<
    'Inverted' | 'Primary' | 'Secondary' | 'Ghost'
  >
}

/**
 * FeaturedGrid variation for CallToAction Slice
 *
 * - **API ID**: `featuredGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceFeaturedGrid = prismic.SharedSliceVariation<
  'featuredGrid',
  Simplify<CallToActionSliceFeaturedGridPrimary>,
  Simplify<CallToActionSliceFeaturedGridItem>
>

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceSocialPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceSocialItem {
  /**
   * Logo field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select a Social Logo
   * - **API ID Path**: call_to_action.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  logo: prismic.SelectField<'Facebook' | 'Instagram' | 'LinkedIn' | 'Yelp'>

  /**
   * Social URL field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the URL of a Social Account
   * - **API ID Path**: call_to_action.items[].social_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_url: prismic.LinkField
}

/**
 * Social variation for CallToAction Slice
 *
 * - **API ID**: `social`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceSocial = prismic.SharedSliceVariation<
  'social',
  Simplify<CallToActionSliceSocialPrimary>,
  Simplify<CallToActionSliceSocialItem>
>

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceBrandGridPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceBrandGridItem {
  /**
   * Brand field in *CallToAction → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].brand
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brand: prismic.ContentRelationshipField<'brand'>

  /**
   * Heading field in *CallToAction → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter a Call to Action
   * - **API ID Path**: call_to_action.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Button Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where should they go?
   * - **API ID Path**: call_to_action.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].button_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_color: prismic.SelectField<
    'Inverted' | 'Primary' | 'Secondary' | 'Ghost'
  >
}

/**
 * Brand Grid variation for CallToAction Slice
 *
 * - **API ID**: `brandGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceBrandGrid = prismic.SharedSliceVariation<
  'brandGrid',
  Simplify<CallToActionSliceBrandGridPrimary>,
  Simplify<CallToActionSliceBrandGridItem>
>

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceProductTypeGridPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceProductTypeGridItem {
  /**
   * Product Type field in *CallToAction → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].product_type
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_type: prismic.ContentRelationshipField<'product_type'>

  /**
   * Heading field in *CallToAction → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter a Call to Action
   * - **API ID Path**: call_to_action.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Button Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where should they go?
   * - **API ID Path**: call_to_action.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].button_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_color: prismic.SelectField<
    'Inverted' | 'Primary' | 'Secondary' | 'Ghost'
  >
}

/**
 * Product Type Grid variation for CallToAction Slice
 *
 * - **API ID**: `productTypeGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceProductTypeGrid = prismic.SharedSliceVariation<
  'productTypeGrid',
  Simplify<CallToActionSliceProductTypeGridPrimary>,
  Simplify<CallToActionSliceProductTypeGridItem>
>

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceServicesGridPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceServicesGridItem {
  /**
   * Service field in *CallToAction → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service: prismic.ContentRelationshipField<'service'>

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField
}

/**
 * ServicesGrid variation for CallToAction Slice
 *
 * - **API ID**: `servicesGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceServicesGrid = prismic.SharedSliceVariation<
  'servicesGrid',
  Simplify<CallToActionSliceServicesGridPrimary>,
  Simplify<CallToActionSliceServicesGridItem>
>

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceExpoPrimary {
  /**
   * Booth Info field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.booth_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  booth_info: prismic.RichTextField

  /**
   * Expo Title field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.primary.expo_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  expo_title: prismic.TitleField

  /**
   * Expo Details field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter info about the expo
   * - **API ID Path**: call_to_action.primary.expo_details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  expo_details: prismic.TitleField
}

/**
 * Expo variation for CallToAction Slice
 *
 * - **API ID**: `expo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceExpo = prismic.SharedSliceVariation<
  'expo',
  Simplify<CallToActionSliceExpoPrimary>,
  never
>

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceFeaturedGrid
  | CallToActionSliceSocial
  | CallToActionSliceBrandGrid
  | CallToActionSliceProductTypeGrid
  | CallToActionSliceServicesGrid
  | CallToActionSliceExpo

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  'call_to_action',
  CallToActionSliceVariation
>

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Content field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSlice = prismic.SharedSlice<'content', ContentSliceVariation>

/**
 * Primary content in *Form → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Name Label field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.name_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_label: prismic.KeyTextField

  /**
   * Name Placeholder field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.name_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_placeholder: prismic.KeyTextField

  /**
   * Email Label field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.email_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_label: prismic.KeyTextField

  /**
   * Email Placeholder field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_placeholder: prismic.KeyTextField

  /**
   * Message Label field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.message_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message_label: prismic.KeyTextField

  /**
   * Message Placeholder field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.message_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message_placeholder: prismic.KeyTextField

  /**
   * Button Text field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Contact variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FormSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Form → Primary*
 */
export interface FormSliceEstimatePrimary {
  /**
   * Name Label field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.name_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_label: prismic.KeyTextField

  /**
   * Name Placeholder field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.name_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_placeholder: prismic.KeyTextField

  /**
   * Email Label field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.email_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_label: prismic.KeyTextField

  /**
   * Email Placeholder field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_placeholder: prismic.KeyTextField

  /**
   * Message Label field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.message_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message_label: prismic.KeyTextField

  /**
   * Message Placeholder field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.message_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message_placeholder: prismic.KeyTextField

  /**
   * Button Text field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Estimate variation for Form Slice
 *
 * - **API ID**: `estimate`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceEstimate = prismic.SharedSliceVariation<
  'estimate',
  Simplify<FormSliceEstimatePrimary>,
  never
>

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault | FormSliceEstimate

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<'form', FormSliceVariation>

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>

  /**
   * Theme field in *Hero → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Base
   * - **API ID Path**: hero.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<'Base' | 'Alternate', 'filled'>
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Button Link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Label field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *Hero → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Inverted
   * - **API ID Path**: hero.items[].button_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_color: prismic.SelectField<
    'Inverted' | 'Primary' | 'Secondary' | 'Ghost',
    'filled'
  >
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Heading field in *ImageWithText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Image Location field in *ImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_with_text.primary.image_location
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_location: prismic.BooleanField

  /**
   * Text field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceTwoColumnPrimary {
  /**
   * Heading field in *ImageWithText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Image Location field in *ImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_with_text.primary.image_location
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_location: prismic.BooleanField

  /**
   * Text field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * TwoColumn variation for ImageWithText Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceTwoColumn = prismic.SharedSliceVariation<
  'twoColumn',
  Simplify<ImageWithTextSliceTwoColumnPrimary>,
  never
>

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceWithIconPrimary {
  /**
   * Heading field in *ImageWithText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Image Location field in *ImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.primary.image_location
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_location: prismic.BooleanField

  /**
   * Text field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Icon field in *ImageWithText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Optionally select an icon
   * - **API ID Path**: image_with_text.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'Garage' | 'Toolbox' | 'Question'>
}

/**
 * WithIcon variation for ImageWithText Slice
 *
 * - **API ID**: `withIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceWithIcon = prismic.SharedSliceVariation<
  'withIcon',
  Simplify<ImageWithTextSliceWithIconPrimary>,
  never
>

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation =
  | ImageWithTextSliceDefault
  | ImageWithTextSliceTwoColumn
  | ImageWithTextSliceWithIcon

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  'image_with_text',
  ImageWithTextSliceVariation
>

/**
 * Primary content in *Scroller → Primary*
 */
export interface ScrollerSliceDefaultPrimary {
  /**
   * Heading field in *Scroller → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Speed field in *Scroller → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Slow
   * - **API ID Path**: scroller.primary.speed
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  speed: prismic.SelectField<'Slow' | 'Medium' | 'Fast', 'filled'>

  /**
   * Scroll Direction field in *Scroller → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: scroller.primary.scroll_direction
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  scroll_direction: prismic.BooleanField
}

/**
 * Primary content in *Scroller → Items*
 */
export interface ScrollerSliceDefaultItem {
  /**
   * Image field in *Scroller → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for Scroller Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScrollerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ScrollerSliceDefaultPrimary>,
  Simplify<ScrollerSliceDefaultItem>
>

/**
 * Primary content in *Scroller → Primary*
 */
export interface ScrollerSliceCarouselPrimary {
  /**
   * Heading field in *Scroller → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField
}

/**
 * Primary content in *Scroller → Items*
 */
export interface ScrollerSliceCarouselItem {
  /**
   * Image field in *Scroller → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Carousel variation for Scroller Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScrollerSliceCarousel = prismic.SharedSliceVariation<
  'carousel',
  Simplify<ScrollerSliceCarouselPrimary>,
  Simplify<ScrollerSliceCarouselItem>
>

/**
 * Slice variation for *Scroller*
 */
type ScrollerSliceVariation = ScrollerSliceDefault | ScrollerSliceCarousel

/**
 * Scroller Shared Slice
 *
 * - **API ID**: `scroller`
 * - **Description**: Scroller
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScrollerSlice = prismic.SharedSlice<
  'scroller',
  ScrollerSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BrandDocument,
      BrandDocumentData,
      BrandDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataFilesItem,
      ProductDocumentDataSlicesSlice,
      ProductTypeDocument,
      ProductTypeDocumentData,
      ProductTypeDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataFooterSocialsItem,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceFeaturedGridPrimary,
      CallToActionSliceFeaturedGridItem,
      CallToActionSliceSocialPrimary,
      CallToActionSliceSocialItem,
      CallToActionSliceBrandGridPrimary,
      CallToActionSliceBrandGridItem,
      CallToActionSliceProductTypeGridPrimary,
      CallToActionSliceProductTypeGridItem,
      CallToActionSliceServicesGridPrimary,
      CallToActionSliceServicesGridItem,
      CallToActionSliceExpoPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceFeaturedGrid,
      CallToActionSliceSocial,
      CallToActionSliceBrandGrid,
      CallToActionSliceProductTypeGrid,
      CallToActionSliceServicesGrid,
      CallToActionSliceExpo,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceEstimatePrimary,
      FormSliceVariation,
      FormSliceDefault,
      FormSliceEstimate,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceTwoColumnPrimary,
      ImageWithTextSliceWithIconPrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      ImageWithTextSliceTwoColumn,
      ImageWithTextSliceWithIcon,
      ScrollerSlice,
      ScrollerSliceDefaultPrimary,
      ScrollerSliceDefaultItem,
      ScrollerSliceCarouselPrimary,
      ScrollerSliceCarouselItem,
      ScrollerSliceVariation,
      ScrollerSliceDefault,
      ScrollerSliceCarousel,
    }
  }
}
