// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>['id']]

type BlogPostDocumentDataSlicesSlice =
  | CallToActionSlice
  | ScrollerSlice
  | ContentSlice
  | ImageWithTextSlice
  | HeroSlice

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the Post Title
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a short preview
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField

  /**
   * Date Published field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.date_published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date_published: prismic.DateField

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    'blog_post',
    Lang
  >

type BrandDocumentDataSlicesSlice = ContentSlice

/**
 * Content for Brand documents
 */
interface BrandDocumentData {
  /**
   * Title field in *Brand*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Logo field in *Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * Description field in *Brand*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Slice Zone field in *Brand*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BrandDocumentDataSlicesSlice> /**
   * Meta Description field in *Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: brand.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: brand.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Brand document from Prismic
 *
 * - **API ID**: `brand`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BrandDocumentData>, 'brand', Lang>

/**
 * Content for Gallery Item documents
 */
interface GalleryItemDocumentData {
  /**
   * Gallery Image field in *Gallery Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_item.gallery_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gallery_image: prismic.ImageField<never>

  /**
   * Related Content field in *Gallery Item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_item.related_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  related_content:
    | prismic.ContentRelationshipField<'blog_post'>
    | prismic.ContentRelationshipField<'portfolio'>
}

/**
 * Gallery Item document from Prismic
 *
 * - **API ID**: `gallery_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GalleryItemDocumentData>,
    'gallery_item',
    Lang
  >

type HomepageDocumentDataSlicesSlice =
  | ReviewsSlice
  | RecentsSlice
  | CallToActionSlice
  | ImageWithTextSlice
  | ContentSlice
  | ScrollerSlice
  | HeroSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

type LocationDocumentDataSlicesSlice =
  | ReviewsSlice
  | RecentsSlice
  | HeroSlice
  | ContentSlice
  | ImageWithTextSlice
  | CallToActionSlice

/**
 * Content for Location documents
 */
interface LocationDocumentData {
  /**
   * Title field in *Location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Featured Image field in *Location*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: location.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Slice Zone field in *Location*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: location.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LocationDocumentDataSlicesSlice> /**
   * Meta Description field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: location.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Location*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: location.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: location.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Location document from Prismic
 *
 * - **API ID**: `location`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LocationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LocationDocumentData>,
    'location',
    Lang
  >

type PageDocumentDataSlicesSlice =
  | EmbedSlice
  | ReviewsSlice
  | LocationsSlice
  | RecentsSlice
  | GallerySlice
  | FormSlice
  | CallToActionSlice
  | ScrollerSlice
  | ContentSlice
  | ImageWithTextSlice
  | HeroSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * TItle field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the Page Title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField

  /**
   * Index field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: page.index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  index: prismic.BooleanField
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

type PortfolioDocumentDataSlicesSlice =
  | EmbedSlice
  | RecentsSlice
  | CallToActionSlice
  | ScrollerSlice
  | ImageWithTextSlice
  | ContentSlice

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * Title field in *Portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the Project Title
   * - **API ID Path**: portfolio.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Date Published field in *Portfolio*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.date_published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date_published: prismic.DateField

  /**
   * Featured Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Excerpt field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField

  /**
   * Slice Zone field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Description field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortfolioDocumentData>,
    'portfolio',
    Lang
  >

/**
 * Item in *Product → Files*
 */
export interface ProductDocumentDataFilesItem {
  /**
   * File field in *Product → Files*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: product.files[].file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  file: prismic.LinkToMediaField<prismic.FieldState, never>
}

type ProductDocumentDataSlicesSlice =
  | EmbedSlice
  | CallToActionSlice
  | RecentsSlice
  | ScrollerSlice
  | ImageWithTextSlice
  | ContentSlice

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the Product Title
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Product Type field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product_type: prismic.ContentRelationshipField<'product_type'>

  /**
   * Brand field in *Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.brand
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  brand: prismic.ContentRelationshipField<'brand'>

  /**
   * Featured Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Status field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Enter the product status
   * - **Default Value**: in stock
   * - **API ID Path**: product.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  status: prismic.SelectField<
    'in stock' | 'low stock' | 'backordered' | 'out of stock' | 'discontinued',
    'filled'
  >

  /**
   * Excerpt field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a shorter description
   * - **API ID Path**: product.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the product
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Files field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.files[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  files: prismic.GroupField<Simplify<ProductDocumentDataFilesItem>>

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ProductDocumentData>, 'product', Lang>

type ProductTypeDocumentDataSlicesSlice = ContentSlice

/**
 * Content for Product Type documents
 */
interface ProductTypeDocumentData {
  /**
   * Title field in *Product Type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the Product Type Title
   * - **API ID Path**: product_type.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Featured Image field in *Product Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Excerpt field in *Product Type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a short product type description
   * - **API ID Path**: product_type.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField

  /**
   * Description field in *Product Type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the product type
   * - **API ID Path**: product_type.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Slice Zone field in *Product Type*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductTypeDocumentDataSlicesSlice> /**
   * Meta Description field in *Product Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product_type.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Product Type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Product Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product_type.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Product Type document from Prismic
 *
 * - **API ID**: `product_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductTypeDocumentData>,
    'product_type',
    Lang
  >

type ServiceDocumentDataSlicesSlice =
  | RecentsSlice
  | CallToActionSlice
  | ScrollerSlice
  | ImageWithTextSlice
  | HeroSlice
  | ContentSlice

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Service Title
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Description field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the service
   * - **API ID Path**: service.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Excerpt field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a shorter description
   * - **API ID Path**: service.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ServiceDocumentData>, 'service', Lang>

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Settings → Footer Socials*
 */
export interface SettingsDocumentDataFooterSocialsItem {
  /**
   * Logo field in *Settings → Footer Socials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_socials[].logo
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  logo: prismic.SelectField<'Facebook' | 'Instagram' | 'LinkedIn' | 'Yelp'>

  /**
   * Social URL field in *Settings → Footer Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_socials[].social_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Domain field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.domain
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  domain: prismic.KeyTextField

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * Phone Number field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_number: prismic.KeyTextField

  /**
   * Site Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_meta_description: prismic.KeyTextField

  /**
   * Site Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  site_meta_image: prismic.ImageField<never>

  /**
   * Site Theme field in *Settings*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_theme
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  site_theme: prismic.SelectField<'Base' | 'Alternate'>

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>

  /**
   * Footer Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footer_logo: prismic.ImageField<never>

  /**
   * Footer Socials field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_socials: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSocialsItem>
  >

  /**
   * Company Information field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter company info
   * - **API ID Path**: settings.company_information
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company_information: prismic.RichTextField

  /**
   * Terms of Service field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter terms of service info
   * - **API ID Path**: settings.terms_of_service
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  terms_of_service: prismic.RichTextField

  /**
   * Design Credit field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optionally give credit to designers.
   * - **API ID Path**: settings.design_credit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  design_credit: prismic.RichTextField

  /**
   * Call To Action field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Text above the phone number
   * - **API ID Path**: settings.call_to_action
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action: prismic.KeyTextField
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >

export type AllDocumentTypes =
  | BlogPostDocument
  | BrandDocument
  | GalleryItemDocument
  | HomepageDocument
  | LocationDocument
  | PageDocument
  | PortfolioDocument
  | ProductDocument
  | ProductTypeDocument
  | ServiceDocument
  | SettingsDocument

/**
 * Item in *CallToAction → Product Recommendation → Primary → Products*
 */
export interface CallToActionSliceProductRecommendationPrimaryProductsItem {
  /**
   * Product field in *CallToAction → Product Recommendation → Primary → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.productRecommendation.primary.products[].product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product: ContentRelationshipFieldWithData<
    [
      {
        id: 'product'
        fields: ['title', 'featured_image', 'status', 'description', 'excerpt']
      },
    ]
  >
}

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Button Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Button Label field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Call to Action
   * - **API ID Path**: call_to_action.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_color: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive'
  >
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *CallToAction → FeaturedGrid → Primary*
 */
export interface CallToActionSliceFeaturedGridPrimary {
  /**
   * Heading field in *CallToAction → FeaturedGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.featuredGrid.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceFeaturedGridItem {
  /**
   * Icon field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select an Icon
   * - **API ID Path**: call_to_action.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    'RiQuestionnaireFill' | 'GiHomeGarage' | 'FaToolbox'
  >

  /**
   * Heading field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a Call to Action
   * - **API ID Path**: call_to_action.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where should they go?
   * - **API ID Path**: call_to_action.items[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].button_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_color: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive'
  >
}

/**
 * FeaturedGrid variation for CallToAction Slice
 *
 * - **API ID**: `featuredGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceFeaturedGrid = prismic.SharedSliceVariation<
  'featuredGrid',
  Simplify<CallToActionSliceFeaturedGridPrimary>,
  Simplify<CallToActionSliceFeaturedGridItem>
>

/**
 * Primary content in *CallToAction → Social → Primary*
 */
export interface CallToActionSliceSocialPrimary {
  /**
   * Heading field in *CallToAction → Social → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.social.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceSocialItem {
  /**
   * Logo field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select a Social Logo
   * - **API ID Path**: call_to_action.items[].logo
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  logo: prismic.SelectField<'Facebook' | 'Instagram' | 'LinkedIn' | 'Yelp'>

  /**
   * Social URL field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the URL of a Social Account
   * - **API ID Path**: call_to_action.items[].social_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >
}

/**
 * Social variation for CallToAction Slice
 *
 * - **API ID**: `social`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceSocial = prismic.SharedSliceVariation<
  'social',
  Simplify<CallToActionSliceSocialPrimary>,
  Simplify<CallToActionSliceSocialItem>
>

/**
 * Primary content in *CallToAction → Brand Grid → Primary*
 */
export interface CallToActionSliceBrandGridPrimary {
  /**
   * Heading field in *CallToAction → Brand Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.brandGrid.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceBrandGridItem {
  /**
   * Brand field in *CallToAction → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].brand
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  brand: prismic.ContentRelationshipField<'brand'>

  /**
   * Heading field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a Call to Action
   * - **API ID Path**: call_to_action.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where should they go?
   * - **API ID Path**: call_to_action.items[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].button_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_color: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive'
  >
}

/**
 * Brand Grid variation for CallToAction Slice
 *
 * - **API ID**: `brandGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceBrandGrid = prismic.SharedSliceVariation<
  'brandGrid',
  Simplify<CallToActionSliceBrandGridPrimary>,
  Simplify<CallToActionSliceBrandGridItem>
>

/**
 * Primary content in *CallToAction → Product Type Grid → Primary*
 */
export interface CallToActionSliceProductTypeGridPrimary {
  /**
   * Heading field in *CallToAction → Product Type Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.productTypeGrid.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceProductTypeGridItem {
  /**
   * Product Type field in *CallToAction → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].product_type
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product_type:
    | prismic.ContentRelationshipField<'product_type'>
    | prismic.ContentRelationshipField<'product'>

  /**
   * Heading field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a Call to Action
   * - **API ID Path**: call_to_action.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where should they go?
   * - **API ID Path**: call_to_action.items[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].button_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_color: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive'
  >
}

/**
 * Product Type Grid variation for CallToAction Slice
 *
 * - **API ID**: `productTypeGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceProductTypeGrid = prismic.SharedSliceVariation<
  'productTypeGrid',
  Simplify<CallToActionSliceProductTypeGridPrimary>,
  Simplify<CallToActionSliceProductTypeGridItem>
>

/**
 * Primary content in *CallToAction → ServicesGrid → Primary*
 */
export interface CallToActionSliceServicesGridPrimary {
  /**
   * Heading field in *CallToAction → ServicesGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.servicesGrid.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceServicesGridItem {
  /**
   * Service field in *CallToAction → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].service
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  service: prismic.ContentRelationshipField<'service'>

  /**
   * Description field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the call to action
   * - **API ID Path**: call_to_action.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Button Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the button say?
   * - **API ID Path**: call_to_action.items[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField
}

/**
 * ServicesGrid variation for CallToAction Slice
 *
 * - **API ID**: `servicesGrid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceServicesGrid = prismic.SharedSliceVariation<
  'servicesGrid',
  Simplify<CallToActionSliceServicesGridPrimary>,
  Simplify<CallToActionSliceServicesGridItem>
>

/**
 * Primary content in *CallToAction → Expo → Primary*
 */
export interface CallToActionSliceExpoPrimary {
  /**
   * Booth Info field in *CallToAction → Expo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.expo.primary.booth_info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  booth_info: prismic.RichTextField

  /**
   * Expo Title field in *CallToAction → Expo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.expo.primary.expo_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  expo_title: prismic.RichTextField

  /**
   * Expo Details field in *CallToAction → Expo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter info about the expo
   * - **API ID Path**: call_to_action.expo.primary.expo_details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  expo_details: prismic.RichTextField
}

/**
 * Expo variation for CallToAction Slice
 *
 * - **API ID**: `expo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceExpo = prismic.SharedSliceVariation<
  'expo',
  Simplify<CallToActionSliceExpoPrimary>,
  never
>

/**
 * Primary content in *CallToAction → Promotion → Primary*
 */
export interface CallToActionSlicePromotionPrimary {
  /**
   * Benefit field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Benefit
   * - **API ID Path**: call_to_action.promotion.primary.benefit
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  benefit: prismic.RichTextField

  /**
   * Promo Code field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.promotion.primary.promo_code
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  promo_code: prismic.KeyTextField

  /**
   * Details field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.promotion.primary.details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField

  /**
   * Image field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.promotion.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Image Shadow field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: call_to_action.promotion.primary.image_shadow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_shadow: prismic.BooleanField

  /**
   * Button Link field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.promotion.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Button Label field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Call to Action
   * - **API ID Path**: call_to_action.promotion.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *CallToAction → Promotion → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.promotion.primary.button_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_color: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive'
  >
}

/**
 * Promotion variation for CallToAction Slice
 *
 * - **API ID**: `promotion`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlicePromotion = prismic.SharedSliceVariation<
  'promotion',
  Simplify<CallToActionSlicePromotionPrimary>,
  never
>

/**
 * Primary content in *CallToAction → Logos → Primary*
 */
export interface CallToActionSliceLogosPrimary {
  /**
   * Heading field in *CallToAction → Logos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.logos.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceLogosItem {
  /**
   * Logo field in *CallToAction → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>
}

/**
 * Logos variation for CallToAction Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceLogos = prismic.SharedSliceVariation<
  'logos',
  Simplify<CallToActionSliceLogosPrimary>,
  Simplify<CallToActionSliceLogosItem>
>

/**
 * Primary content in *CallToAction → Product Recommendation → Primary*
 */
export interface CallToActionSliceProductRecommendationPrimary {
  /**
   * Heading field in *CallToAction → Product Recommendation → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Call to Action Heading
   * - **API ID Path**: call_to_action.productRecommendation.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Products field in *CallToAction → Product Recommendation → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.productRecommendation.primary.products[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  products: prismic.GroupField<
    Simplify<CallToActionSliceProductRecommendationPrimaryProductsItem>
  >
}

/**
 * Product Recommendation variation for CallToAction Slice
 *
 * - **API ID**: `productRecommendation`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceProductRecommendation =
  prismic.SharedSliceVariation<
    'productRecommendation',
    Simplify<CallToActionSliceProductRecommendationPrimary>,
    never
  >

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceFeaturedGrid
  | CallToActionSliceSocial
  | CallToActionSliceBrandGrid
  | CallToActionSliceProductTypeGrid
  | CallToActionSliceServicesGrid
  | CallToActionSliceExpo
  | CallToActionSlicePromotion
  | CallToActionSliceLogos
  | CallToActionSliceProductRecommendation

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<
  'call_to_action',
  CallToActionSliceVariation
>

/**
 * Primary content in *Content → Default → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Content field in *Content → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSlice = prismic.SharedSlice<'content', ContentSliceVariation>

/**
 * Primary content in *Embed → Default → Primary*
 */
export interface EmbedSliceDefaultPrimary {
  /**
   * Heading field in *Embed → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add a heading level 2 or 3
   * - **API ID Path**: embed.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * URL field in *Embed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the iframe url
   * - **API ID Path**: embed.default.primary.url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  url: prismic.KeyTextField
}

/**
 * Default variation for Embed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<EmbedSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Embed*
 */
type EmbedSliceVariation = EmbedSliceDefault

/**
 * Embed Shared Slice
 *
 * - **API ID**: `embed`
 * - **Description**: Embed
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedSlice = prismic.SharedSlice<'embed', EmbedSliceVariation>

/**
 * Primary content in *Form → Contact → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Name Label field in *Form → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_label: prismic.KeyTextField

  /**
   * Name Placeholder field in *Form → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.name_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_placeholder: prismic.KeyTextField

  /**
   * Email Label field in *Form → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField

  /**
   * Email Placeholder field in *Form → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_placeholder: prismic.KeyTextField

  /**
   * Message Label field in *Form → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.message_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_label: prismic.KeyTextField

  /**
   * Message Placeholder field in *Form → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.message_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_placeholder: prismic.KeyTextField

  /**
   * Button Text field in *Form → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField
}

/**
 * Contact variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FormSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Form → Estimate → Primary*
 */
export interface FormSliceEstimatePrimary {
  /**
   * Name Label field in *Form → Estimate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.estimate.primary.name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_label: prismic.KeyTextField

  /**
   * Name Placeholder field in *Form → Estimate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.estimate.primary.name_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_placeholder: prismic.KeyTextField

  /**
   * Email Label field in *Form → Estimate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.estimate.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField

  /**
   * Email Placeholder field in *Form → Estimate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.estimate.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_placeholder: prismic.KeyTextField

  /**
   * Message Label field in *Form → Estimate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.estimate.primary.message_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_label: prismic.KeyTextField

  /**
   * Message Placeholder field in *Form → Estimate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.estimate.primary.message_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_placeholder: prismic.KeyTextField

  /**
   * Button Text field in *Form → Estimate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.estimate.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField
}

/**
 * Estimate variation for Form Slice
 *
 * - **API ID**: `estimate`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceEstimate = prismic.SharedSliceVariation<
  'estimate',
  Simplify<FormSliceEstimatePrimary>,
  never
>

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault | FormSliceEstimate

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSlice = prismic.SharedSlice<'form', FormSliceVariation>

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Title field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GallerySliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySlice = prismic.SharedSlice<'gallery', GallerySliceVariation>

/**
 * Item in *Hero → Default → Primary → Buttons*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Button Link field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link'
  >
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>

  /**
   * Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Button Link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Button Label field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Color field in *Hero → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: hero.items[].button_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_color: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive',
    'filled'
  >
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *ImageWithText → Default → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Heading field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Image field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Image Link field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  image_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Image Location field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_with_text.default.primary.image_location
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_location: prismic.BooleanField

  /**
   * Text field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField

  /**
   * Call To Action field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add a call to action
   * - **API ID Path**: image_with_text.default.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  call_to_action: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      'default' | 'destructive' | 'ghost' | 'link' | 'outline' | 'secondary'
    >
  >
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *ImageWithText → TwoColumn → Primary*
 */
export interface ImageWithTextSliceTwoColumnPrimary {
  /**
   * Heading field in *ImageWithText → TwoColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.twoColumn.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Image field in *ImageWithText → TwoColumn → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.twoColumn.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Image Location field in *ImageWithText → TwoColumn → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_with_text.twoColumn.primary.image_location
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_location: prismic.BooleanField

  /**
   * Text field in *ImageWithText → TwoColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.twoColumn.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField
}

/**
 * TwoColumn variation for ImageWithText Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSliceTwoColumn = prismic.SharedSliceVariation<
  'twoColumn',
  Simplify<ImageWithTextSliceTwoColumnPrimary>,
  never
>

/**
 * Primary content in *ImageWithText → WithIcon → Primary*
 */
export interface ImageWithTextSliceWithIconPrimary {
  /**
   * Heading field in *ImageWithText → WithIcon → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.withIcon.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Image field in *ImageWithText → WithIcon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.withIcon.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Image Location field in *ImageWithText → WithIcon → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.withIcon.primary.image_location
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_location: prismic.BooleanField

  /**
   * Text field in *ImageWithText → WithIcon → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.withIcon.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField

  /**
   * Icon field in *ImageWithText → WithIcon → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Optionally select an icon
   * - **API ID Path**: image_with_text.withIcon.primary.icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<'Garage' | 'Toolbox' | 'Question'>
}

/**
 * WithIcon variation for ImageWithText Slice
 *
 * - **API ID**: `withIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSliceWithIcon = prismic.SharedSliceVariation<
  'withIcon',
  Simplify<ImageWithTextSliceWithIconPrimary>,
  never
>

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation =
  | ImageWithTextSliceDefault
  | ImageWithTextSliceTwoColumn
  | ImageWithTextSliceWithIcon

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  'image_with_text',
  ImageWithTextSliceVariation
>

/**
 * Primary content in *Locations → Default → Primary*
 */
export interface LocationsSliceDefaultPrimary {
  /**
   * Heading field in *Locations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optionally add a heading
   * - **API ID Path**: locations.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Description field in *Locations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optionally add a description
   * - **API ID Path**: locations.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *Locations → Items*
 */
export interface LocationsSliceDefaultItem {
  /**
   * Location field in *Locations → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: locations.items[].location
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  location: prismic.ContentRelationshipField<'location'>
}

/**
 * Default variation for Locations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LocationsSliceDefaultPrimary>,
  Simplify<LocationsSliceDefaultItem>
>

/**
 * Slice variation for *Locations*
 */
type LocationsSliceVariation = LocationsSliceDefault

/**
 * Locations Shared Slice
 *
 * - **API ID**: `locations`
 * - **Description**: Locations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationsSlice = prismic.SharedSlice<
  'locations',
  LocationsSliceVariation
>

/**
 * Primary content in *Recents → Default → Primary*
 */
export interface RecentsSliceDefaultPrimary {
  /**
   * Heading field in *Recents → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recents.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Type field in *Recents → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: blog_post
   * - **API ID Path**: recents.default.primary.type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<'blog_post' | 'portfolio', 'filled'>
}

/**
 * Default variation for Recents Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RecentsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RecentsSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Recents → Location → Primary*
 */
export interface RecentsSliceLocationPrimary {
  /**
   * Heading field in *Recents → Location → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recents.location.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Type field in *Recents → Location → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: blog_post
   * - **API ID Path**: recents.location.primary.type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<'blog_post' | 'portfolio', 'filled'>

  /**
   * Location field in *Recents → Location → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select a location
   * - **API ID Path**: recents.location.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  location: prismic.SelectField<
    | 'Burnaby'
    | 'Coquitlam'
    | 'Delta'
    | 'Langley'
    | 'Maple Ridge'
    | 'New Westminster'
    | 'North Vancouver'
    | 'Richmond'
    | 'Surrey'
    | 'Vancouver'
    | 'West Vancouver'
    | 'White Rock'
  >

  /**
   * Service field in *Recents → Location → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: recents.location.primary.service
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  service: prismic.SelectField<'All' | 'Installation' | 'Repair'>
}

/**
 * Location variation for Recents Slice
 *
 * - **API ID**: `location`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RecentsSliceLocation = prismic.SharedSliceVariation<
  'location',
  Simplify<RecentsSliceLocationPrimary>,
  never
>

/**
 * Slice variation for *Recents*
 */
type RecentsSliceVariation = RecentsSliceDefault | RecentsSliceLocation

/**
 * Recents Shared Slice
 *
 * - **API ID**: `recents`
 * - **Description**: Recents
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RecentsSlice = prismic.SharedSlice<'recents', RecentsSliceVariation>

/**
 * Item in *Reviews → Manual → Primary → Reviews*
 */
export interface ReviewsSliceManualPrimaryReviewsItem {
  /**
   * Reviewer Name field in *Reviews → Manual → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.manual.primary.reviews[].reviewer_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reviewer_name: prismic.KeyTextField

  /**
   * Rating field in *Reviews → Manual → Primary → Reviews*
   *
   * - **Field Type**: Number
   * - **Placeholder**: How many stars was the review?
   * - **API ID Path**: reviews.manual.primary.reviews[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField

  /**
   * Review Date field in *Reviews → Manual → Primary → Reviews*
   *
   * - **Field Type**: Date
   * - **Placeholder**: When was the review received?
   * - **API ID Path**: reviews.manual.primary.reviews[].review_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  review_date: prismic.DateField

  /**
   * Show Date field in *Reviews → Manual → Primary → Reviews*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: reviews.manual.primary.reviews[].show_date
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_date: prismic.BooleanField

  /**
   * Review Text field in *Reviews → Manual → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.manual.primary.reviews[].review_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  review_text: prismic.KeyTextField
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>

/**
 * Primary content in *Reviews → Manual → Primary*
 */
export interface ReviewsSliceManualPrimary {
  /**
   * Reviews field in *Reviews → Manual → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.manual.primary.reviews[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  reviews: prismic.GroupField<Simplify<ReviewsSliceManualPrimaryReviewsItem>>
}

/**
 * Manual variation for Reviews Slice
 *
 * - **API ID**: `manual`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsSliceManual = prismic.SharedSliceVariation<
  'manual',
  Simplify<ReviewsSliceManualPrimary>,
  never
>

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault | ReviewsSliceManual

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsSlice = prismic.SharedSlice<'reviews', ReviewsSliceVariation>

/**
 * Item in *Scroller → Carousel → Primary → Items*
 */
export interface ScrollerSliceCarouselPrimaryItemsItem {
  /**
   * image field in *Scroller → Carousel → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.carousel.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *Scroller → Carousel → Primary*
 */
export interface ScrollerSliceCarouselPrimary {
  /**
   * Heading field in *Scroller → Carousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.carousel.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField

  /**
   * Desktop Columns field in *Scroller → Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: How many slides to show on desktop
   * - **Default Value**: 1
   * - **API ID Path**: scroller.carousel.primary.desktop_columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  desktop_columns: prismic.SelectField<'1' | '2' | '3' | '4', 'filled'>

  /**
   * Items field in *Scroller → Carousel → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.carousel.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<ScrollerSliceCarouselPrimaryItemsItem>>
}

/**
 * Primary content in *Scroller → Items*
 */
export interface ScrollerSliceCarouselItem {
  /**
   * Image field in *Scroller → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: scroller.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>
}

/**
 * Carousel variation for Scroller Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollerSliceCarousel = prismic.SharedSliceVariation<
  'carousel',
  Simplify<ScrollerSliceCarouselPrimary>,
  Simplify<ScrollerSliceCarouselItem>
>

/**
 * Slice variation for *Scroller*
 */
type ScrollerSliceVariation = ScrollerSliceCarousel

/**
 * Scroller Shared Slice
 *
 * - **API ID**: `scroller`
 * - **Description**: Scroller
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollerSlice = prismic.SharedSlice<
  'scroller',
  ScrollerSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BrandDocument,
      BrandDocumentData,
      BrandDocumentDataSlicesSlice,
      GalleryItemDocument,
      GalleryItemDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LocationDocument,
      LocationDocumentData,
      LocationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataFilesItem,
      ProductDocumentDataSlicesSlice,
      ProductTypeDocument,
      ProductTypeDocumentData,
      ProductTypeDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataFooterSocialsItem,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceFeaturedGridPrimary,
      CallToActionSliceFeaturedGridItem,
      CallToActionSliceSocialPrimary,
      CallToActionSliceSocialItem,
      CallToActionSliceBrandGridPrimary,
      CallToActionSliceBrandGridItem,
      CallToActionSliceProductTypeGridPrimary,
      CallToActionSliceProductTypeGridItem,
      CallToActionSliceServicesGridPrimary,
      CallToActionSliceServicesGridItem,
      CallToActionSliceExpoPrimary,
      CallToActionSlicePromotionPrimary,
      CallToActionSliceLogosPrimary,
      CallToActionSliceLogosItem,
      CallToActionSliceProductRecommendationPrimaryProductsItem,
      CallToActionSliceProductRecommendationPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceFeaturedGrid,
      CallToActionSliceSocial,
      CallToActionSliceBrandGrid,
      CallToActionSliceProductTypeGrid,
      CallToActionSliceServicesGrid,
      CallToActionSliceExpo,
      CallToActionSlicePromotion,
      CallToActionSliceLogos,
      CallToActionSliceProductRecommendation,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      EmbedSlice,
      EmbedSliceDefaultPrimary,
      EmbedSliceVariation,
      EmbedSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceEstimatePrimary,
      FormSliceVariation,
      FormSliceDefault,
      FormSliceEstimate,
      GallerySlice,
      GallerySliceDefaultPrimary,
      GallerySliceVariation,
      GallerySliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceTwoColumnPrimary,
      ImageWithTextSliceWithIconPrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      ImageWithTextSliceTwoColumn,
      ImageWithTextSliceWithIcon,
      LocationsSlice,
      LocationsSliceDefaultPrimary,
      LocationsSliceDefaultItem,
      LocationsSliceVariation,
      LocationsSliceDefault,
      RecentsSlice,
      RecentsSliceDefaultPrimary,
      RecentsSliceLocationPrimary,
      RecentsSliceVariation,
      RecentsSliceDefault,
      RecentsSliceLocation,
      ReviewsSlice,
      ReviewsSliceManualPrimaryReviewsItem,
      ReviewsSliceManualPrimary,
      ReviewsSliceVariation,
      ReviewsSliceDefault,
      ReviewsSliceManual,
      ScrollerSlice,
      ScrollerSliceCarouselPrimaryItemsItem,
      ScrollerSliceCarouselPrimary,
      ScrollerSliceCarouselItem,
      ScrollerSliceVariation,
      ScrollerSliceCarousel,
    }
  }
}
