// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  call_to_action: dynamic(() => import('./CallToAction')),
  content: dynamic(() => import('./Content')),
  embed: dynamic(() => import('./Embed')),
  form: dynamic(() => import('./Form')),
  gallery: dynamic(() => import('./Gallery')),
  hero: dynamic(() => import('./Hero')),
  image_with_text: dynamic(() => import('./ImageWithText')),
  locations: dynamic(() => import('./Locations')),
  recents: dynamic(() => import('./Recents')),
  reviews: dynamic(() => import('./Reviews')),
  scroller: dynamic(() => import('./Scroller')),
  table: dynamic(() => import('./Table')),
}
