// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  call_to_action: dynamic(() => import('./CallToAction')),
  content: dynamic(() => import('./Content')),
  form: dynamic(() => import('./Form')),
  gallery: dynamic(() => import('./Gallery')),
  hero: dynamic(() => import('./Hero')),
  image_with_text: dynamic(() => import('./ImageWithText')),
  recents: dynamic(() => import('./Recents')),
  scroller: dynamic(() => import('./Scroller')),
}
